CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  refresh_token TEXT
);

ALTER TABLE users
ADD COLUMN name VARCHAR(100) NOT NULL;
