export const AuditoriaAction = Object.freeze({
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAIL: "LOGIN_FAIL",
	LOGOUT: "LOGOUT",
	ROLE_CHANGED: "ROLE_CHANGED",
	PLAN_UPDATED: "PLAN_UPDATED",
	PLAN_UPDATE_ERROR: "PLAN_UPDATE_ERROR",
	CREATED_NEW_PLAN: "CREATED_NEW_PLAN",
	ERROR_CREATED_NEW_PLAN: "ERROR_CREATED_NEW_PLAN",
});
